// <auto-generated />
using System;
using DATN_Quản_lý_phòng_gym_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATN_Quản_lý_phòng_gym_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMonths = 1,
                            IsActive = true,
                            PackageName = "Cơ Bản",
                            Price = 500000m
                        },
                        new
                        {
                            Id = 2,
                            DurationMonths = 1,
                            IsActive = true,
                            PackageName = "Cao Cấp",
                            Price = 1000000m
                        },
                        new
                        {
                            Id = 3,
                            DurationMonths = 1,
                            IsActive = true,
                            PackageName = "Ưu Tú",
                            Price = 1700000m
                        });
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionName = "USER_VIEW"
                        },
                        new
                        {
                            PermissionId = 2,
                            PermissionName = "USER_CREATE"
                        },
                        new
                        {
                            PermissionId = 3,
                            PermissionName = "USER_UPDATE"
                        },
                        new
                        {
                            PermissionId = 4,
                            PermissionName = "USER_DELETE"
                        });
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Trainer"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Member"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        });
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("PackageId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 2, 6, 21, 35, 2, 226, DateTimeKind.Local).AddTicks(3440),
                            Email = "admin@gym.com",
                            FullName = "Admin System",
                            IsActive = true,
                            PasswordHash = "$2a$11$q0hxXqmWq2cygeru.qTvkuKAEvFAMJcM5Ah8OPL9bgq59BPdVgnhG",
                            Phone = "0900000001",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 21, 35, 2, 366, DateTimeKind.Local).AddTicks(1462),
                            Email = "trainer@gym.com",
                            FullName = "Huấn luyện viên",
                            IsActive = true,
                            PasswordHash = "$2a$11$UDP09JFFbcvMAXt0dw/oP.ahz5NixVqiHT1uRFStpU3kv77zAtUcy",
                            Phone = "0900000002",
                            Username = "trainer"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 2, 6, 21, 35, 2, 500, DateTimeKind.Local).AddTicks(1794),
                            Email = "member@gym.com",
                            FullName = "Hội viên",
                            IsActive = true,
                            PasswordHash = "$2a$11$7bBsT2dmQkCfaoTnAxDtpOEHYtPQ.xWZc1Qwnf3h0/NqaNT9L1Bhm",
                            Phone = "0900000003",
                            Username = "member"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 2, 6, 21, 35, 2, 629, DateTimeKind.Local).AddTicks(6774),
                            Email = "staff@gym.com",
                            FullName = "Nhân viên",
                            IsActive = true,
                            PasswordHash = "$2a$11$x5/ory/dcgbJf/82PKT0ReiR9Ojm8YY/Ph9V9TvweT1DrM7z5SZ.K",
                            Phone = "0900000004",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.RolePermission", b =>
                {
                    b.HasOne("DATN_Quản_lý_phòng_gym_Backend.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_Quản_lý_phòng_gym_Backend.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.User", b =>
                {
                    b.HasOne("DATN_Quản_lý_phòng_gym_Backend.Models.Package", "Package")
                        .WithMany("Users")
                        .HasForeignKey("PackageId");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.UserRole", b =>
                {
                    b.HasOne("DATN_Quản_lý_phòng_gym_Backend.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_Quản_lý_phòng_gym_Backend.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.Package", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DATN_Quản_lý_phòng_gym_Backend.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
